import { chromium } from 'playwright';
import fs from 'fs';
const base = process.env.BASE || 'http://127.0.0.1:8765/';
const browser = await chromium.launch({ args: ['--no-sandbox', '--disable-dev-shm-usage'] });
const ctx = await browser.newContext();
const page = await ctx.newPage();
await page.addInitScript(() => { globalThis.NOISE_MODEL_URL = location.origin + '/.impeccable/build/model.bin'; });
page.on('crash', () => console.log('PAGE CRASHED'));
page.on('close', () => console.log('page closed'));
page.on('pageerror', (e) => console.log('pageerror:', e.message));
page.on('console', (m) => console.log('console', m.type(), m.text().slice(0, 300)));
await page.goto(base, { waitUntil: 'networkidle' });
const step = async (label, fn) => { try { const r = await page.evaluate(fn); console.log(label, 'OK', JSON.stringify(r)); } catch (e) { console.log(label, 'FAILED', e.message.split('\n')[0]); } };
await step('caches', async () => { const c = await caches.open('noise-test'); await c.put('/x', new Response('hi')); const m = await c.match('/x'); return await m.text(); });
await step('fetch model (no cache)', async () => { const { MODEL_URL } = await import('./js/stems.js'); const r = await fetch(MODEL_URL); const ab = await r.arrayBuffer(); return ab.byteLength; });
await step('ensureModel', async () => { const { ensureModel, modelCached } = await import('./js/stems.js'); const got = []; const b = await ensureModel((g, t) => got.push(g)); return { returnedBytes: b ? b.byteLength : null, cached: await modelCached(), ticks: got.length }; });
await step('worker init', async () => {
  const w = new Worker('js/separate.worker.js');
  const c = await caches.open('noise-demucs-v1'); const { MODEL_URL } = await import('./js/stems.js'); const r = await c.match(MODEL_URL); const model = await r.arrayBuffer();
  return await new Promise((res, rej) => { const t = setTimeout(() => rej(new Error('timeout')), 60000); w.onmessage = (e) => { clearTimeout(t); res(e.data.type); w.terminate(); }; w.onerror = (e) => { clearTimeout(t); rej(new Error(e.message)); }; w.postMessage({ type: 'init', model }); });
});
await browser.close();
