// NOISE smoke: load the demo through the real UI, confirm analysis, playback, sliders, render.
import { chromium } from 'playwright';
const base = process.env.BASE || 'http://127.0.0.1:8765/';
const browser = await chromium.launch({ args: ['--no-sandbox', '--autoplay-policy=no-user-gesture-required'] });
const page = await browser.newPage({ viewport: { width: 1280, height: 900 } });
const errors = [];
page.on('pageerror', (e) => errors.push('pageerror: ' + e.message));
page.on('console', (m) => { if (m.type() === 'error') errors.push('console: ' + m.text()); });
page.on('requestfailed', (r) => errors.push('reqfail: ' + r.url()));
await page.goto(base, { waitUntil: 'networkidle' });
console.log('title:', await page.title());
console.log('stage:', await page.evaluate(() => document.body.dataset.stage));
const t0 = Date.now();
await page.click('#try');
await page.waitForFunction(() => document.body.dataset.stage === 'deck', null, { timeout: 120000 });
console.log('analysis took', ((Date.now() - t0) / 1000).toFixed(1), 's');
const a = await page.evaluate(() => { const a = window.noise.analysis; return { bpm: +a.bpm.toFixed(2), beats: a.beats.length, key: a.key, phase: a.phase, start: +a.startSec.toFixed(2), dur: +a.duration.toFixed(1) }; });
console.log('analysis:', JSON.stringify(a));
await page.waitForTimeout(2500);
const st = await page.evaluate(() => ({ playing: window.noise.ph.playing, pos: +window.noise.ph.position().toFixed(2), events: window.noise.ph.arr.events.length, bars: window.noise.ph.arr.bars.length, drop: window.noise.ph.arr.dropBar, meta: document.querySelector('#now-meta').textContent }));
console.log('playing:', JSON.stringify(st));
const lv = await page.evaluate(async () => { const g = window.noise.ph.live; const out = []; for (let i = 0; i < 6; i++) { await new Promise((r) => setTimeout(r, 500)); const w = g.tape.wave(); let s = 0; for (let k = 0; k < w.length; k++) { const v = (w[k] - 128) / 128; s += v * v; } out.push(+Math.sqrt(s / w.length).toFixed(3)); } return out; });
console.log('rms:', lv.join(' '));
await page.evaluate(() => { const i = document.querySelector('input[data-param=flip]'); i.value = 0.6; i.dispatchEvent(new Event('input', { bubbles: true })); });
await page.waitForTimeout(300);
console.log('flip set:', await page.evaluate(() => ({ flip: window.noise.ph.params.flip, planned: window.noise.ph.arr.bars.filter((b) => b.plan).length, playing: window.noise.ph.playing })));
await page.click('.chip[data-preset=memphis]');
await page.waitForTimeout(300);
console.log('preset:', await page.evaluate(() => ({ slow: window.noise.ph.params.slow, on: document.querySelector('.chip.is-on').textContent, playing: window.noise.ph.playing })));
await page.click('#reroll');
await page.click('#play'); await page.waitForTimeout(200);
const paused = await page.evaluate(() => ({ playing: window.noise.ph.playing, at: +window.noise.ph._pausedAt.toFixed(2) }));
await page.click('#play'); await page.waitForTimeout(400);
console.log('pause/resume:', JSON.stringify(paused), await page.evaluate(() => window.noise.ph.playing));
const r = await page.evaluate(async () => {
  const t = performance.now();
  window.noise.ph.stop();
  const mix = await window.noise.ph.render();
  const { encodeWav, encodeMp3 } = await import('./js/export.js');
  const wav = encodeWav(mix);
  const t1 = performance.now();
  const mp3 = await encodeMp3(mix, 128);
  let peak = 0; const d = mix.getChannelData(0); for (let i = 0; i < d.length; i += 7) peak = Math.max(peak, Math.abs(d[i]));
  return { renderSec: +((t1 - t) / 1000).toFixed(1), mp3Sec: +((performance.now() - t1) / 1000).toFixed(1), dur: +mix.duration.toFixed(1), wavKB: Math.round(wav.size / 1024), mp3KB: Math.round(mp3.size / 1024), peak: +peak.toFixed(3) };
});
console.log('render:', JSON.stringify(r));
const m = await browser.newPage({ viewport: { width: 390, height: 844 }, isMobile: true, hasTouch: true });
await m.goto(base, { waitUntil: 'networkidle' });
console.log('mobile overflow:', await m.evaluate(() => document.documentElement.scrollWidth > document.documentElement.clientWidth));
await m.screenshot({ path: '/data/pat/.hermes/cache/scratch/noise2/mobile-intake.png' });
await page.screenshot({ path: '/data/pat/.hermes/cache/scratch/noise2/desk-deck.png' });
await page.click('#another'); await page.waitForTimeout(200);
await page.screenshot({ path: '/data/pat/.hermes/cache/scratch/noise2/desk-intake.png' });
console.log('ERRORS:', errors.length ? errors.join('\n') : 'none');
await browser.close();
