import { chromium } from 'playwright';
const browser = await chromium.launch({ args: ['--no-sandbox', '--autoplay-policy=no-user-gesture-required', '--use-fake-ui-for-media-stream', '--use-fake-device-for-media-stream'] });
const page = await browser.newPage({ viewport: { width: 1440, height: 900 } });
const errors = [];
page.on('console', (m) => { if (m.type() === 'error' || m.type() === 'warning') errors.push(`[${m.type()}] ${m.text()}`); });
page.on('pageerror', (e) => errors.push('[pageerror] ' + e.message));
await page.goto('http://127.0.0.1:8765/index.html', { waitUntil: 'networkidle' });
await page.waitForTimeout(500);
console.log('title:', await page.title());
console.log('devices rendered:', await page.locator('#rack .device').count());
console.log('knobs:', await page.locator('.knob').count());
console.log('selector buttons:', await page.locator('.selector .sel').count());
await page.click('#coin');
await page.waitForTimeout(1800);
const state = await page.evaluate(async () => {
  const a = window.noise; const eng = a.engine;
  await new Promise(r => setTimeout(r, 400));
  const m = eng.master.meter();
  const car = a.song.devices.find(d => d.type === 'carousel');
  return { ctxState: eng.ctx.state, playing: eng.playing, step: eng.currentStep(), rms: m.rms, peak: m.peak, slices: car.audio?.slices?.length, sampleDur: car.audio?.buffer?.duration, bpm: eng.effectiveBpm(), lit: document.body.classList.contains('is-lit') };
});
console.log('after coin:', JSON.stringify(state));
const rmsSamples = [];
for (let i = 0; i < 8; i++) { await page.waitForTimeout(350); rmsSamples.push(await page.evaluate(() => +window.noise.engine.master.meter().rms.toFixed(3))); }
console.log('rms over time:', rmsSamples.join(' '));
const rt = await page.evaluate(async () => {
  const a = window.noise;
  const data = a.engine.serialize();
  const json = JSON.stringify(data);
  const mod = await import('/js/song.js');
  const back = mod.validateSong(JSON.parse(json));
  const car = back.devices.find(d => d.type === 'carousel');
  return { kb: Math.round(json.length / 1024), devices: back.devices.length, notes: back.devices.reduce((s, d) => s + d.patterns.reduce((x, p) => x + p.notes.length, 0), 0), wavPrefix: car.audio.wav.slice(0, 22), slices: car.audio.slices.length, bars: back.arrangement.bars, title: back.title };
});
console.log('roundtrip:', JSON.stringify(rt));
await page.click('.selector .sel[data-lane="5"][data-step="3"]'); await page.waitForTimeout(80);
console.log('selector toggled on:', await page.evaluate(() => document.querySelector('.selector .sel[data-lane="5"][data-step="3"]').classList.contains('is-on')));
await page.focus('[data-device="hearse"] .knob__cap');
await page.keyboard.press('ArrowUp');
console.log('hearse decay after arrow:', await page.evaluate(() => window.noise.song.devices.find(d => d.type === 'hearse').params.decay));
await page.locator('#screw input').fill('-4');
await page.locator('#screw input').dispatchEvent('input');
console.log('screw bpm:', await page.evaluate(() => Math.round(window.noise.engine.effectiveBpm())));
await page.click('#lathe-resample');
await page.waitForFunction(() => window.noise.lathe.buffer, null, { timeout: 30000 });
console.log('lathe:', await page.evaluate(() => ({ dur: window.noise.lathe.buffer.duration.toFixed(2), cuts: window.noise.lathe.slices.length, name: window.noise.lathe.name })));
await page.click('#lathe-commit');
await page.waitForTimeout(300);
console.log('carousel after press:', await page.evaluate(() => { const c = window.noise.song.devices.find(d => d.type === 'carousel'); return { name: c.audio.name, slices: c.audio.slices.length, keys: document.querySelectorAll('.slice-keys .sel').length }; }));
await page.keyboard.press('Control+z');
console.log('after undo selector on:', await page.evaluate(() => document.querySelector('.selector .sel[data-lane="5"][data-step="3"]').classList.contains('is-on')));
const box = await page.locator('.editor__canvas').boundingBox();
await page.mouse.click(box.x + 84 + 30 * 5 + 10, box.y + 22 + 22 * 2 + 10);
await page.waitForTimeout(100);
console.log('editor:', await page.evaluate(() => ({ mode: window.noise.editor.mode, dev: window.noise.editor.deviceId, pat: window.noise.editor.patId, notes: window.noise.song.devices.find(d=>d.id===window.noise.editor.deviceId).patterns[0].notes.length })));
await page.click('.tab[data-mode="song"]');
await page.waitForTimeout(100);
console.log('song mode:', await page.evaluate(() => window.noise.engine.mode));
const wavBytes = await page.evaluate(async () => { const ab = await window.noise.engine.renderMixdown(); const v = new DataView(ab); return { bytes: ab.byteLength, riff: String.fromCharCode(v.getUint8(0), v.getUint8(1), v.getUint8(2), v.getUint8(3)), sr: v.getUint32(24, true) }; });
console.log('mixdown:', JSON.stringify(wavBytes));
await page.evaluate(() => window.noise.engine.stop());
await page.evaluate(() => window.scrollTo(0, 0));
await page.screenshot({ path: '.impeccable/review/desktop.png', fullPage: true });
const m = await browser.newPage({ viewport: { width: 390, height: 844 }, isMobile: true, hasTouch: true });
await m.goto('http://127.0.0.1:8765/index.html', { waitUntil: 'networkidle' });
await m.waitForTimeout(400);
console.log('mobile overflow:', await m.evaluate(() => document.documentElement.scrollWidth > document.documentElement.clientWidth ? `YES ${document.documentElement.scrollWidth}` : 'no'));
await m.screenshot({ path: '.impeccable/review/mobile.png', fullPage: true });
console.log('ERRORS:', errors.length ? errors.join('\n') : 'none');
await browser.close();
